### ISSUE TITLE
<aside> inside <dt> is invalid HTML

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#129]
https://validator.nu/?doc=https%3A%2F%2Fhtml.spec.whatwg.org%2F gives a bunch of errors of the sort

> Error: The element aside must not appear as a descendant of the dt element.
>
> From line 5689, column 133; to line 5689, column 171
>
> `/a></code><aside class="mdn-anno wrapped before"><butto`

I'm not sure what the right fix is here; perhaps just using `<div>` instead of `<aside>`? @sideshowbarker

**Comment by domenic** [comment]
I guess we could also consider changing the HTML spec authoring rules... `<aside>` being "sectioning content" is a bit strange, for cases like this.

**Comment by sideshowbarker** [comment]
> I'm not sure what the right fix is here; perhaps just using `<div>` instead of `<aside>`? 

Yes, I think so — for now at least. See https://github.com/whatwg/wattsi/pull/131

> I guess we could also consider changing the HTML spec authoring rules... `<aside>` being "sectioning content" is a bit strange, for cases like this.

Yes. I think we should reconsider that restriction. It seems overly prescriptive. Given that `aside` began life as a basically a synonym for `footnote`, and that it’s easily imaginable that authors/developers may want, for example, to footnote `dt` content (which is essentially what we are doing with the MDN annos for `dt` content), then I don’t think we should be preventing/discouraging authors/developers from being able to do that.

So it’s not clear to me what problem we are trying to help avoid authors/developers avoid by making `aside` within `dt` non-conforming. Unless it’s clear to others what the problem is, then I suggest we consider dropping that restriction.

Also in general I don’t know that `aside` should be considered "sectioning content". I suspect there are use cases other than the one we ran into here in which it’s also not a natural fit to be treating `aside` as "sectioning content".

**Comment by domenic** [comment]
I decided not to file a HTML spec issue here because, when writing it up, I realized that `aside` is allowed inside `dd`. It's just `dt` that's special. And I think it's reasonable to say that the "definition term" should not have an "aside", but instead you should move your "asides" into the "definition data" for that term.

For Wattsi, we could add code to move it into the `<dd>` (probably as the first child), or we could just stick with `<div>`.
