### ISSUE TITLE
Automatic omission of IDL from dev edition no longer happens

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#84]
This was broken by syntax hightlighting. Offending lines:

```pas
         if (IsHighlighterTarget(Element, ClassValue) and AnsiContainsStr(ClassValue, 'idl') and (Variant = vDEV)) then
         begin
            Result := False;
         end
```

**Comment by sideshowbarker** [comment]
oofs, will fix asap

**Comment by sideshowbarker** [comment]
So it turns out this wasn’t broken by syntax highlighting. Instead it was broken by https://github.com/whatwg/html/pull/3768 (“Add `<code>` element inside applicable `<pre>` elements”).

That would have also broken the previous wattsi code here too — regardless of whether or not we’d updated the wattsi code for syntax-highlighting support (because the previous code was just checking for `class=idl` only on `pre` elements, so the https://github.com/whatwg/html/pull/3768 move of the `class=idl` to `code` children means that previous code would have quit work anyway).

**Comment by domenic** [comment]
Sorry, I had to revert #85, as it turns out it leaves the `</pre>` tags in the dev edition. My bad for not testing things locally before merging...

**Comment by sideshowbarker** [comment]
> Sorry, I had to revert #85, as it turns out it leaves the </pre> tags in the dev edition. My bad for not testing things locally before merging...

Nah, my bad — I was aware of that but (mistakenly…) thought that I’d corrected it on the branch. Anyway, #88 should fix it.
